@startuml
skinparam backgroundColor #EEEBDC

skinparam sequence {
	ArrowColor DeepSkyBlue
	ActorBorderColor DeepSkyBlue
	LifeLineBorderColor black
	LifeLineBackgroundColor #A9DCDF

	ParticipantBorderColor DeepSkyBlue
	ParticipantBackgroundColor DodgerBlue
	ParticipantFontName Impact
	ParticipantFontSize 20
	ParticipantFontColor #A9DCDF

	ArrowColor Olive
    	ActorFontName Courier

    	ActorBackgroundColor<< Human >> Gold
}

left to right direction
title 用例图

actor 教师

actor 学生

actor 用户

用户 <|-- 教师

用户 <|-down- 管理员

用户 <|-up- 学生


package 用户用例集 {
用户 --> (登录)

用户 --> (登出)

用户 --> (查看用户信息)

用户 --> (修改密码)

}




package 管理员用例集{

管理员 --> (添加学生信息)
管理员 --> (添加教师信息)
管理员 --> (添加班级信息)
管理员 --> (添加课程信息)

}
package 教师用例集 {

教师 --> (成绩管理)
教师 --> (课程列表)
教师 --> (学生列表)
教师 --> (添加实验)
}
package 学生用例集{

学生 --> (课程列表)
学生 --> (选择学期)
学生 --> (学生列表)
学生 --> (查看成绩)
学生 --> (选课)
学生 --> (实验选择)
学生 --> (提交实验)
}
@enduml