@startuml
skinparam backgroundColor #EEEBDC

skinparam sequence {
	ArrowColor DeepSkyBlue
	ActorBorderColor DeepSkyBlue
	LifeLineBorderColor black
	LifeLineBackgroundColor #A9DCDF
	
	ParticipantBorderColor DeepSkyBlue
	ParticipantBackgroundColor DodgerBlue
	ParticipantFontName Impact
	ParticipantFontSize 20
	ParticipantFontColor #A9DCDF
}

hide footbox
title 维护管理员信息 用例
actor 系统
boundary 账号判断
control 业务控制
database 操作信息


autonumber
group 管理员账号合法性验证
activate 账号判断
	系统 -> 账号判断 :  输入管理员账号信息
	activate 业务控制
		账号判断 -> 业务控制 : 获取账号信息
deactivate 账号判断
		activate 操作信息
			业务控制 -> 操作信息 : 比对账号密码合法性
			操作信息 --> 业务控制 : 账号合法
end
group 维护管理员信息
			系统 -> 业务控制 : 输入管理员新信息
			业务控制 -> 操作信息 : 修改管理员信息
			操作信息 -> 业务控制 : 返回操作结果
		deactivate 操作信息
	业务控制 -> 系统 : 返回维护管理员信息结果
	deactivate 业务控制
	

end

@enduml