@startuml
title 用户列表的顺序图
actor 用户
database 数据库
用户 -> 数据库: 查看所有学生信息
数据库 -> 学生: 根据用用户列表查看该用户的权限
alt 如果用户是老师
	用户 -> grades:批改学生的作业
	grades -> 数据库: 上传学生的成绩
	用户 -> 数据库:查看学生的详细信息
else 如果用户是学生
    学生 --> 用户:每个学生的信息
end

@enduml